### PR TITLE
Display update changelog if requested on `self-update`

### LINKED ISSUE #19: Show release notes when running `self-update` command
Right now the `self-update` subcommand only shows the latest version that was updated to:

```plaintext
🚀 Rokit has been updated successfully!

You are now running version a.b.c, updated from x.y.z.
```

It might be useful to show release notes for the new version, or all versions between the old and new. Rokit already fetches full release information for self-updating, which includes the release description, it is just left unused.

- Release notes may be quite long, it could be a good idea to prompt the user (`Do you want to view release notes for a.b.c?`) before showing them.
- Showing release notes with pretty formatting (bolding) would make this more useful, and also require parsing markdown. This parsing is typically not too complicated but may increase Rokit's binary size.

### PR DESCRIPTION
**Pull request by CompeyDev**
This can potentially be expanded to display changelogs for updates on all tools, rather than just Rokit itself.

Closes #19.

### CODE REVIEW

**Review by filiptibell — CHANGES_REQUESTED** [review]
Nice, this will be a great improvement in UX for updating! I'm not familiar with the libraries used here but they look fine to me.
I am slightly concerned about the diff in `Cargo.lock` though - it seems like it is pulling in large dependencies such as `image`, an svg renderer, openssl, and some others that we don't need for basic changelogs in the terminal. We probably need to disable some features in these new deps 🤔

**Comment by CompeyDev** [comment]
> I am slightly concerned about the diff in Cargo.lock though 

I played around with the features for mdcat - but it doesn't improve the changes in Cargo.lock much. There aren't any features on mdcat to disable HTTP requests either. By itself, mdcat isn't much of a library, but more of a CLI tool, which has a library interface too.

I can probably swap it out for another markdown renderer, but I've not found any other alternatives to have satisfactory render outputs.

**Comment by filiptibell** [comment]
It seems like `mdcat` is mostly a light wrapper around [`pulldown-cmark-mdcat`](https://docs.rs/pulldown-cmark-mdcat/2.3.0/pulldown_cmark_mdcat/), and that crate has features for these large dependencies that can be disabled. Maybe we can use that directly instead?
Or if all else fails, we could do some very rudimentary markdown rendering of our own using a simpler parser-only markdown crate. I don't think we're going to have release changelogs with anything beyond basic headers and lists for Rokit anytime soon, at least 😄

**Comment by CompeyDev** [comment]
> Maybe we can use that directly instead?

I currently am already disabling its features - but I'll try seeing if using it as a direct rather than peer dependency makes any difference.

**Comment by filiptibell** [comment]
> I currently am already disabling its features - but I'll try seeing if using it as a direct rather than peer dependency makes any difference.

Yeah, you'll have to remove `mdcat` since it uses default (all) features for that crate. The cargo book section on [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) clarifies this a bit - features are always treated as *additive* and any one of your other dependencies enabling them will mean that they're enabled across the board

**Review by filiptibell — APPROVED** [review]
LGTM 👍 just need the conflict resolved

**Review by filiptibell — APPROVED** [review]

**Pull request merged**
