### PR TITLE
Fix accepting different token types

### PR DESCRIPTION
**Pull request by Midnightific**
Fixes accepting different token types

If no one’s got objections I’ve started writing up a draft of a GitHub action for rokit so I’d love to be the one to publish it if that’s okay.

Removing regex was @Dekkonot's suggestion so if you can somehow add him as a coauthor that'd be great!

### CODE REVIEW

**Comment by Midnightific** [comment]
Sorry just realised I left the test in there, if someone could remove that then that’d be great 😅

**Comment by Paracosm-Daemon** [comment]
Glad to see this. I switched to Rokit recently for a few things I'm working on, and the token auth issue completely severed my ability to publish packages via GitHub Actions.

> If no one’s got objections I’ve started writing up a draft of a GitHub action for rokit so I’d love to be the one to publish it if that’s okay.

Sidenote- [this was already made](https://github.com/kalrnlo/setup-rokit/tree/v1.0.0/), but it's currently nonfunctional due tot he aforementioned issue.

**Comment by Midnightific** [comment]
Yeah I didn't know that until yesterday but as long as someone's done it then that's fantastic! 😄

**Review by filiptibell — APPROVED** [review]
Thank you for the PR and for fixing this! It seems like tracking down an official source on *exactly* what formats and prefixes the github tokens can have is challenging... so a solution like this one, matching against *any github-like token*, probably fits Rokit best. 
I dont imagine it will cause any issues since the `rokit authenticate github` command also checks that the token is valid using the API.

**Pull request merged**
